import re, json, subprocess
from playwright.sync_api import sync_playwright
BASE='http://127.0.0.1:8099'
AXE=open('/tmp/a11y-check/node_modules/axe-core/axe.min.js').read()
fallos=[]
def comprobar(n,c,extra=''):
    print(('ok    ' if c else 'FALLO ')+n+(('  → '+str(extra)) if extra and not c else ''))
    if not c: fallos.append(n)
def ctx(b,w=1280,tema='light'):
    return b.new_context(viewport={'width':w,'height':900},ignore_https_errors=True,bypass_csp=True,reduced_motion='reduce',color_scheme=tema)
def entrar(pg,q):
    pg.goto(BASE+'/acceso'); f=pg.locator('#formEntrar')
    f.locator('[name=email]').fill(f'{q}@pruebas.test'); f.locator('[name=clave]').fill(f'clave-de-prueba-{q}')
    f.locator('[type=submit]').click(); pg.wait_for_url(re.compile(r'/panel'),timeout=15000)
    pg.wait_for_selector('[data-nav] a[data-ruta="ficha"]',timeout=15000)
def axe(pg,sel):
    pg.add_script_tag(content=AXE)
    return pg.evaluate("async(s)=>(await axe.run(s,{runOnly:['wcag2a','wcag2aa']})).violations.map(v=>v.id+':'+v.nodes.length+' '+v.nodes[0].target.join(' '))",sel)
with sync_playwright() as p:
    b=p.chromium.launch(); errs=[]
    c=ctx(b); pg=c.new_page(); pg.on('pageerror',lambda e: errs.append(str(e)))
    entrar(pg,'mates')
    pg.click('[data-ruta="ficha"]'); pg.wait_for_selector('[data-form-ficha]',timeout=10000)
    comprobar('mates: abre Mi ficha enlazada a su nombre', 'Mi ficha' in pg.locator('h1').first.inner_text())
    pg.set_input_files('[data-subir-retrato]','/tmp/sbtest/foto.jpg'); pg.wait_for_selector('[data-foto-vista] img',timeout=15000)
    foto=pg.locator('input[name=foto]').input_value()
    comprobar('mates: foto subida a personas/<slug>', '/personas/marga-orell-cernuda/' in foto and foto.endswith('.webp'), foto)
    comprobar('mates: vista previa con foto', pg.locator('[data-vista-tarjeta] img').count()==1)
    pg.fill('#fFrase','Las matemáticas se entienden haciendo.')
    pg.fill('#fBio','Corta.'); pg.click('[data-form-ficha] [type=submit]'); pg.wait_for_timeout(400)
    comprobar('mates: pide mínimo en la presentación', 'muy corta' in pg.locator('body').inner_text())
    pg.fill('#fBio','Soy profesora de Matemáticas y jefa del departamento. Me gusta que los alumnos descubran las matemáticas resolviendo problemas reales.\n\nCoordino la olimpiada matemática del colegio.')
    pg.fill('#fDesde','2010'); pg.fill('#fCorreo','marga@gmail.com'); pg.click('[data-form-ficha] [type=submit]'); pg.wait_for_timeout(400)
    comprobar('mates: rechaza correo personal', 'del colegio' in pg.locator('body').inner_text())
    pg.fill('#fCorreo','marga.orell@colegionsdolores.es'); pg.click('[data-form-ficha] [type=submit]'); pg.wait_for_timeout(1200)
    comprobar('mates: guarda la ficha', 'Ficha guardada' in pg.locator('body').inner_text())
    comprobar('mates: no ve Fichas del personal', pg.locator('[data-ruta="fichas"]').count()==0)
    pg.screenshot(path='/tmp/claude-0/shots/panel-ficha-1280.png', full_page=True)
    c.close()
    # entrada del blog como mates (directo en la base de datos, con su sesión simulada)
    subprocess.run(['psql','-h','127.0.0.1','-U','postgres','-d','nsd','-qc',"""select set_config('request.jwt.claims','{"sub":"22222222-2222-2222-2222-222222222222","role":"authenticated"}',false); set role authenticated; insert into public.entradas (ambito_id,titulo,resumen,cuerpo,categoria,fecha) values ('dep-matematicas','Olimpiada matemática','Resumen','Cuerpo de la entrada.','eso',current_date);"""],env={'PGPASSWORD':'pg','PATH':'/usr/bin:/bin'},check=True)
    slug=subprocess.run(['psql','-h','127.0.0.1','-U','postgres','-d','nsd','-Atc',"select slug||'|'||coalesce(ficha,'') from public.entradas limit 1"],env={'PGPASSWORD':'pg','PATH':'/usr/bin:/bin'},capture_output=True,text=True).stdout.strip()
    comprobar('entrada guarda la ficha del autor', slug.endswith('|marga-orell-cernuda'), slug)
    for w,tema in [(1280,'light'),(375,'dark')]:
        c=ctx(b,w,tema); pg=c.new_page(); pg.on('pageerror',lambda e: errs.append(str(e)))
        pg.goto(BASE+'/centro/departamentos/matematicas'); pg.wait_for_timeout(1500)
        card=pg.locator('a.persona[data-persona="marga-orell-cernuda"]').first
        comprobar(f'{w}: tarjeta con foto en el departamento', card.locator('img').count()==1)
        card.click(); pg.wait_for_selector('dialog.ficha-ventana[open] .ficha-nombre',timeout=8000); pg.wait_for_timeout(800)
        t=pg.locator('dialog.ficha-ventana').inner_text()
        comprobar(f'{w}: ficha flotante con bio y cargos de varios departamentos', 'resolviendo problemas' in t and 'Matemáticas' in t and 'Ciencias' in t, t[:300])
        comprobar(f'{w}: ficha con sus entradas del blog', 'Olimpiada matemática' in t)
        comprobar(f'{w}: años en el colegio', 'desde 2010' in t)
        pg.screenshot(path=f'/tmp/claude-0/shots/ficha-{w}-{tema}.png')
        comprobar(f'{w}: accesibilidad de la ficha', not axe(pg,'dialog.ficha-ventana'), axe(pg,'dialog.ficha-ventana'))
        pg.keyboard.press('Escape'); pg.wait_for_timeout(400)
        comprobar(f'{w}: Escape cierra y devuelve el foco', not pg.locator('dialog[open]').count() and pg.evaluate("document.activeElement.dataset.persona")=='marga-orell-cernuda')
        pg.goto(BASE+'/centro/organigrama'); pg.wait_for_timeout(1500)
        comprobar(f'{w}: organigrama con su foto', pg.locator('a.persona[data-persona="marga-orell-cernuda"] img').count()>=1)
        pg.goto(BASE+'/blog/entrada?e='+slug.split('|')[0]); pg.wait_for_timeout(2000)
        comprobar(f'{w}: entrada con tarjeta del autor', pg.locator('.entrada-autor a.persona img').count()==1)
        pg.goto(BASE+'/centro/persona?p=marga-orell-cernuda'); pg.wait_for_timeout(1500)
        comprobar(f'{w}: página propia', 'Marga Orell Cernuda' in pg.locator('h1').last.inner_text() or pg.locator('.ficha--pagina h1').count()==1)
        pg.screenshot(path=f'/tmp/claude-0/shots/persona-{w}-{tema}.png', full_page=True)
        comprobar(f'{w}: accesibilidad página', not axe(pg,'main'), axe(pg,'main'))
        pg.goto(BASE+'/centro/equipo-directivo'); pg.wait_for_timeout(1200)
        pg.locator('a.persona[data-persona]').first.click(); pg.wait_for_selector('dialog[open]',timeout=5000)
        comprobar(f'{w}: equipo directivo abre ficha', 'Coordinadora' in pg.locator('dialog').inner_text())
        c.close()
    # dirección
    c=ctx(b); pg=c.new_page(); pg.on('pageerror',lambda e: errs.append(str(e)))
    entrar(pg,'admin'); pg.click('[data-ruta="fichas"]'); pg.wait_for_selector('.pnl-fichas__item',timeout=10000)
    n=pg.locator('.pnl-fichas__item').count()
    comprobar('admin: lista todas las personas de la web', n>=35, n)
    pg.locator('[data-crear-ficha="Laura Ruiz Yerpes"]').click(); pg.wait_for_selector('[data-form-ficha]',timeout=8000)
    comprobar('admin: crea y abre ficha', 'Laura Ruiz Yerpes' in pg.locator('h1').first.inner_text())
    pg.fill('#fFrase','Coordino Infantil.'); pg.click('[data-form-ficha] [type=submit]'); pg.wait_for_timeout(1000)
    comprobar('admin: edita ficha ajena', 'Ficha guardada' in pg.locator('body').inner_text())
    pg.select_option('#fCuenta', label='Marga Orell Cernuda · mates@pruebas.test'); pg.click('[data-enlazar] [type=submit]'); pg.wait_for_timeout(800)
    comprobar('admin: enlaza cuenta', 'Cuenta actualizada' in pg.locator('body').inner_text())
    pg.goto(BASE+'/panel#fichas'); pg.wait_for_selector('.pnl-fichas__item'); pg.screenshot(path='/tmp/claude-0/shots/panel-fichas-375.png')
    c.close()
    comprobar('sin errores de JavaScript', not errs, errs[:3])
    b.close()
print(f'\n{len(fallos)} fallos'); raise SystemExit(1 if fallos else 0)
